// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Cirrious.MvvmCross.Touch.Views;
using Cirrious.MvvmCross.Binding.Touch.Views;
using News.Core.ViewModels;
using Cirrious.MvvmCross.Binding.BindingContext;

namespace News.iOS.Views
{
    public partial class ArticleView : MvxViewController<ArticleViewModel>
	{
        private MvxImageViewLoader _imageLoader;
        public ArticleView () : base ("ArticleView", null)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
            Title = ViewModel.Title;

            _imageLoader = new MvxImageViewLoader (() => ImageView);

            var set = this.CreateBindingSet<ArticleView, ArticleViewModel> ();
            set.Bind (ScrollView).For ("Visibility").To (vm => vm.Body).WithConversion ("Visibility");
            set.Bind (ActivityIndicator).For ("Visibility").To (vm => vm.Body).WithConversion ("InvertedVisibility");
            set.Bind (_imageLoader).To (vm => vm.ImageUrl);
        //    set.Bind (TextView).To (vm => vm.Body);
			set.Apply ();

            ViewModel.PropertyChanged += (object sender, System.ComponentModel.PropertyChangedEventArgs e) => {
                if (e.PropertyName == "Body") {
                    NSError error = null;
                    var attributedString = new NSAttributedString(ViewModel.Body, new NSAttributedStringDocumentAttributes { DocumentType = NSDocumentType.HTML }, ref error);
                    TextView.AttributedText = attributedString;
                }
            };
        }
	}
}
