// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Cirrious.MvvmCross.Touch.Views;
using Cirrious.MvvmCross.Binding.Touch.Views;
using News.Core.ViewModels;
using Cirrious.MvvmCross.Binding.BindingContext;

namespace News.iOS
{
	public partial class HomeView : MvxViewController
	{
        public HomeView () : base ("HomeView", null)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
            Title = "Home";

            var source = new MvxStandardTableViewSource (TableView, "TitleText Title");
            TableView.Source = source;

			var set = this.CreateBindingSet<HomeView, HomeViewModel> ();
            set.Bind (TableView).For ("Visibility").To (vm => vm.CategorySummaries).WithConversion ("Visibility");
            set.Bind (ActivityIndicator).For ("Visibility").To (vm => vm.CategorySummaries).WithConversion ("InvertedVisibility");
            set.Bind (source).To (vm => vm.CategorySummaries);
			set.Apply ();
		}
	}
}
